### ISSUE TITLE
installing failure 

### ISSUE THREAD

**Issue by Ning0Luo** [samee/obliv-c#44] opened 2017-09-21 19:53 UTC
I  tried to install obliv-c in my pc however failed with following error . 
I think that may be caused by version of my  fedora and GCC.
My system is Fedora release 26
My GCC version is  7.2.1
Thanks

`printf /home/nl437/obliv-c/lib > ocamlpath
/usr/bin/install -c -m 644 ocamlpath share/cil
rm -f ocamlpath
make[1]: Leaving directory '/home/nl437/obliv-c'
bin/oblivcc -c src/ext/oblivc/copy.oc -o _build/copy.oo -I src/ext/oblivc -O3
Cannot find GNUCC version
ar cr _build/libobliv.a _build/obliv_bits.o _build/ot.o _build/dualex.o _build/atomic_queue.o _build/commitReveal.o _build/obliv_network_utils.o _build/bcrandom.o _build/privacy-free.o _build/psi.o _build/nnob.o _build/copy.o _build/copy.oo
ar: _build/copy.oo: No such file or directory
make: *** [Makefile:121: _build/libobliv.a] Error 1`

**Comment by samee** [comment] 2017-09-22 06:03
Pasting private email message from Ning since it has more error messages:

```
printf /home/nl437/obliv-c/lib > ocamlpath
/usr/bin/install -c -m 644 ocamlpath share/cil
rm -f ocamlpath
make[1]: Leaving directory '/home/nl437/obliv-c'
bin/oblivcc -c src/ext/oblivc/copy.oc -o _build/copy.oo -I src/ext/oblivc -O3
Cannot find GNUCC version
ar cr _build/libobliv.a _build/obliv_bits.o _build/ot.o _build/dualex.o _build/atomic_queue.o _build/commitReveal.o _build/obliv_network_utils.o _build/bcrandom.o _build/privacy-free.o _build/psi.o _build/nnob.o _build/copy.o _build/copy.oo
ar: _build/copy.oo: No such file or directory
make: *** [Makefile:121: _build/libobliv.a] Error 1
```

It seems like Cilly (a dependency that runs with oblivcc) is failing at this point: https://github.com/cil-project/cil/blob/develop/lib/perl5/App/Cilly.pm.in#L2208

**Comment by samee** [comment] 2017-09-22 06:06
Hi Ning, thanks for reaching out.

Can you please run `gcc -dumpversion` and tell me what the output is? If that still says 7.2.1, it would be great if you could do some Perl debugging, since I can't seem to reproduce the problem on my end. Try printing out `join(' ', @{$self->{PPARGS}})` and pasting it here, for instance, and see if we can spot any problem.

**Comment by Ning0Luo** [comment] 2017-09-22 14:54
Hi,
I tried that just now and i am pretty sure about the version.
Maybe I should do something further?


[nl437@cs-pc-3 obliv-c]$ gcc -dumpversion
7
[nl437@cs-pc-3 obliv-c]$ join(' ', @{$self->{PPARGS}})
bash: syntax error near unexpected token `' ','
[nl437@cs-pc-3 obliv-c]$

**Comment by jackdoerner** [comment] 2017-09-23 23:19
I am currently in the process of upgrading my workstation to F26, so I will see if I can reproduce.
EDIT: Can confirm, this error occurs under F26.
EDIT2: It appears that `gcc -dumpversion` only gives the major version number now, and that there is a new GCC flag that continues the old behavior, `gcc -dumpfullversion`. Unfortunately, this means that we have to pick a different flag based on the version of GCC (and the new flag isn't supported by old GCC). It may be that we need to parse `-dumpversion` and collect from `-dumpfullversion` if the major version is >= 7. I can confirm that changing the flag outright allows Obliv-C to compile on my machine.
EDIT3: it seems SuSE has been patching GCC to behave this way for a while, which means CIL probably doesn't work there.

**Comment by schoppmp** [comment] 2018-02-16 11:23
I'm currently having the same problem on my Ubuntu 17.10 VM:
```bash
$ bin/oblivcc -c src/ext/oblivc/copy.oc -o _build/copy.oo -I src/ext/oblivc -O3
Cannot find GNUCC version
$ gcc -dumpversion
7
$ gcc -dumpfullversion
7.2.0
```
Interestingly, on my Laptop (running Arch Linux), `gcc -dumpversion` gives the full version number:
```zsh
> gcc -dumpversion
7.2.1
> gcc -dumpfullversion
7.2.1
```
As you can see, both GCC versions differ only in the build number. Even if I downgrade GCC on my Arch machine to 7.2.0, `-dumpversion` gives the full version. Seems like this problem really depends on how GCC is built, which differs between distributions. See, for example, this thread:
https://gcc.gnu.org/ml/gcc-patches/2017-01/msg00593.html

**Comment by schoppmp** [comment] 2018-02-16 14:21
I suggest cherry-picking 305eaf3 into [`obliv-c`](https://github.com/samee/obliv-c/commits/obliv-c) so that this issue can be closed without having to wait for everything in the [`ocaml-update`](https://github.com/samee/obliv-c/commits/ocaml-update) branch to be fully tested.

**Comment by samee** [comment] 2018-02-18 17:59
Merged in the entire branch. I think I'm reasonably happy with it, given we've had a fair number of successes so far.

**Closed as completed by samee** 2018-02-18 17:59 UTC
